# Generated by Django 3.0.8 on 2020-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200824_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
