# Generated by Django 3.0.8 on 2020-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20200826_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
