# Generated by Django 3.0.8 on 2020-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20200826_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
