# Generated by Django 3.0.8 on 2020-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_auto_20200826_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
