# Generated by Django 3.1 on 2020-08-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='no_question_solved',
            field=models.IntegerField(default=0),
        ),
    ]
