# Generated by Django 3.1 on 2020-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_response_no_question_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
