# Generated by Django 3.1 on 2020-08-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_response_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question_attempted',
            field=models.TextField(default=0),
        ),
    ]
